apiVersion: v1
kind: Namespace
metadata:
  name: bar
  labels:
    environment-id: env_5dc71d5f-fa10-44f6-9cac-86571e2aa825
    project-id: project_fcbfd9aa-ae26-4b5c-bc4b-87ba7314a3d3
    project-name: kelcier
    environment-name: prod
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
